<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<p style="text-align: center;"> <a href="https://ondiande.com/"> <img src="https://i.ibb.co/mvHRT4S/ONDIA-logo.png" width="500" height="200" class="img-fluid" alt="ONDIA LOGO" title="INTELLIGENT & PERSONALIZED SOLUTIONS TO DATA ANALYSIS AND DATA MANAGEMENT ISSUES"> </a> </p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;">
  Intelligent & Personalized Solutions
</div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:300%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [84]:
# YOUR CODE IS HERE
import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [85]:
# YOUR CODE IS HERE
my_array = np.array([5, 10, 15, 20, 25])
my_array


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [86]:
# YOUR CODE IS HERE
my_zeros = np.zeros((5,5))


### 4. Generate an array of 4x4 with ones and assign data type as int.

In [87]:
# YOUR CODE IS HERE
my_ones = np.ones((4,4), dtype=int)

### 5. Make all the values of the array above with the value of 7.

In [88]:
# YOUR CODE IS HERE
np.ones((4,4), dtype=int)*7


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [89]:
# YOUR CODE IS HERE
np.full((4,4), 7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [90]:
# YOUR CODE IS HERE
np.arange(2,17,2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [91]:
# YOUR CODE IS HERE

np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [92]:
# YOUR CODE IS HERE
np.linspace(0,24,25).reshape(5,5)


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [93]:
# YOUR CODE IS HERE
np.random.rand(5)


array([0.64911867, 0.64564448, 0.68088139, 0.20599346, 0.96479534])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [94]:
# YOUR CODE IS HERE
np.random.normal(size=(5,5))


array([[-0.00540595, -0.25641269,  0.3034318 , -0.78349697,  1.88028262],
       [-0.08388276,  1.00452795,  1.76130823, -1.01635315, -1.00448395],
       [-1.16551648, -1.21036312, -1.27317528,  0.49483673,  2.22570746],
       [ 1.48587736,  0.94529849,  3.04180334, -0.54789918,  0.68638075],
       [-0.59789506,  0.08613705,  0.56707014, -0.88702103,  0.28989522]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [95]:
# YOUR CODE IS HERE
np.random.randint(20,50,(3,4))


array([[49, 49, 34, 23],
       [38, 20, 31, 45],
       [22, 34, 23, 21]], dtype=int32)

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [96]:
# YOUR CODE IS HERE
ranarr = np.random.randint(1,48,48)



In [97]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)
ranarr.reshape(6,8)


array([[ 3,  7, 39,  3, 31, 19,  1, 33],
       [30, 31, 28, 30,  8,  8, 27, 14],
       [37, 19, 26, 11,  5, 47, 24, 42],
       [24, 13, 27,  8, 23,  2, 19, 46],
       [ 9, 42, 31, 17, 44,  2, 40, 40],
       [10,  7, 38, 33, 13, 43, 37, 33]], dtype=int32)

In [98]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr.reshape(6,-1)


array([[ 3,  7, 39,  3, 31, 19,  1, 33],
       [30, 31, 28, 30,  8,  8, 27, 14],
       [37, 19, 26, 11,  5, 47, 24, 42],
       [24, 13, 27,  8, 23,  2, 19, 46],
       [ 9, 42, 31, 17, 44,  2, 40, 40],
       [10,  7, 38, 33, 13, 43, 37, 33]], dtype=int32)

In [99]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr.reshape(-1,8)


array([[ 3,  7, 39,  3, 31, 19,  1, 33],
       [30, 31, 28, 30,  8,  8, 27, 14],
       [37, 19, 26, 11,  5, 47, 24, 42],
       [24, 13, 27,  8, 23,  2, 19, 46],
       [ 9, 42, 31, 17, 44,  2, 40, 40],
       [10,  7, 38, 33, 13, 43, 37, 33]], dtype=int32)

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [100]:
# YOUR CODE IS HERE
mat = np.arange(1,17).reshape(4,4)

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [101]:
# YOUR CODE IS HERE
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [102]:
# YOUR CODE IS HERE
mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [103]:
mat[1,::2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [104]:
# YOUR CODE IS HERE
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [105]:
# YOUR CODE IS HERE
mat[1,0], mat[3,2]

(np.int64(5), np.int64(77))

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [106]:
# YOUR CODE IS HERE
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [107]:
# LET US REMEMBER OUR ARRAY OF "mat"
mat
# YOUR CODE IS HERE



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [108]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

# YOUR CODE IS HERE
mat[mat<10]


array([1, 2, 4, 5, 6, 8, 9])

In [109]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE
mat[mat>12]


array([77, 77, 77, 13, 14, 77, 16])

In [110]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE
mat[mat<10] + mat[mat>12]


array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [111]:
# YOUR CODE IS HERE
sum = mat[mat<10] + mat[mat>12]
sum.std()


np.float64(29.700546274093877)

### 22. Get the sum of the 2nd column in the original "mat".

In [112]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
mat[:,1].sum()


np.int64(32)

In [113]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

# YOUR CODE IS HERE
mat[:,2] = np.array([3,7,11,15])
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [114]:
# YOUR CODE IS HERE



### 23. Get the median, mean and std of 3rd column in "mat".

In [115]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
print(mat[:,2].mean())
print(mat[:,2].std())


9.0
4.47213595499958


In [116]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

# YOUR CODE IS HERE
mat[:, 2:3]


array([[ 3],
       [ 7],
       [11],
       [15]])

In [117]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

# YOUR CODE IS HERE
mat[2,:]


array([ 9, 10, 11, 12])

In [118]:
# LET US GET MEDIAN VALUE

# YOUR CODE IS HERE



In [119]:
# LET US GET MEAN VALUE

# YOUR CODE IS HERE



In [120]:
# LET US GET STANDART DEVIATION (std) VALUE

# YOUR CODE IS HERE



## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [125]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [126]:
# LET US READ Salaries.csv

# YOUR CODE IS HERE

df = pd.read_csv("Salaries.csv")




In [127]:
# LET US LOOK AT THE FIRST 5 ROWS

# YOUR CODE IS HERE
df.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [128]:
# LET US GET A SAMPLE

# YOUR CODE IS HERE
df.sample(1)


Id     EmployeeName          JobTitle   BasePay  OvertimePay  \
101960  101961  Bobby R Rollins  Transit Operator  22655.04      1693.01   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
101960    883.59  13352.06  25231.64           38583.7  2013    NaN   

               Agency  Status  
101960  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [129]:
# YOUR CODE IS HERE
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [130]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

# YOUR CODE IS HERE
df.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [139]:
# YOUR CODE IS HERE
df["Year"].value_counts()


Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [140]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE
df["Year"].nunique()


4

In [141]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE
df["Year"].unique()


array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [142]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE
df["TotalPay"].max()


np.float64(567595.43)

In [143]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE
df["TotalPay"].mean()


np.float64(74768.32197169267)

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [144]:
# YOUR CODE IS HERE
df[df["TotalPay"]>df["TotalPay"].mean()]


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [146]:
# YOUR CODE IS HERE
total = df[df["TotalPay"]>df["TotalPay"].mean()].shape[0]
total



69489

### How much does ALBERT PARDINI make money (including benefits)?

In [150]:
# YOUR CODE IS HERE
df[df["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]


2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [152]:
# YOUR CODE IS HERE
df.sort_values("TotalPay", ascending=True).head(1)["EmployeeName"]


148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [155]:
# YOUR CODE IS HERE
df["JobTitle"].unique()


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], shape=(2159,), dtype=object)

### List the top 3 least common Jobs in the dataset.

In [157]:
# YOUR CODE IS HERE
df["JobTitle"].value_counts().tail(3)


JobTitle
ADMINISTRATOR, SFGH MEDICAL CENTER    1
CHIEF OF POLICE                       1
Special Assistant 8                   1
Name: count, dtype: int64

### How many people earned more than avg in 2012?

In [169]:
# YOUR CODE IS HERE
df[(df["TotalPayBenefits"] > df["TotalPayBenefits"].mean()) & (df["Year"]==2012)].count().iloc[0]


np.int64(20366)

### How many people have a title of Manager in their jobs?

In [180]:
# USE APPLY FUNCTION

df["JobTitle"] = df["JobTitle"].astype("str")# YOUR CODE IS HERE
df['JobTitle'].apply(lambda x: "MANAGER" in str(x).upper()).sum()



np.int64(4110)

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [185]:
# YOUR CODE IS HERE
sal_new = df.iloc[:,[0,1,2,7,8]]
sal_new


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [186]:
# YOUR CODE IS HERE
sal_new_df = sal_new.loc[:,["EmployeeName","TotalPayBenefits"]]


Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [190]:
# YOUR CODE IS HERE

mask = (df["TotalPayBenefits"]>df["TotalPayBenefits"].min()) & (df["TotalPayBenefits"]<df["TotalPayBenefits"].mean())
df[mask].loc[:,["EmployeeName", 'TotalPayBenefits']]

EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<hr>

<p style="background-color:#FDFEFE; font-family:newtimeroman; color:#635EA7; font-size:350%; text-align:center; border-radius:10px 10px;">End of The Assignment - 1</p>

# <span style="color:#DA55E5">**Now. it's time to relax!**<span>
    
![Image_Assignment](https://i.ibb.co/jZD3Mqb/relaxing.jpg)
   

<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>